### ISSUE TITLE
Are Beats and Buds Supposed To Match?

### ISSUE THREAD

**Issue by Jdemig** [words/double-metaphone#11]
Pretty much what the title says. They both match to PT but I would say they are not phonetically similar.

**Comment by wooorm** [comment]
Hey!
This is an implementation of an algorithm.
Questions about whether this is the case in the original algo, can go there.
If the original algorithm does do this differently than this project, that's an issue here.
But, quickly, trying to gauge this: I pronounce beats and buds quite differently

**Comment by Jdemig** [comment]
Looks like the other implementations have the same problem
